name: local_date
description: >-
  The library for representation of local date an date of birth in
  the Gregorian calendar (ISO 8601).
topics:
  - date
  - date-of-birth
  - birthday
version: 0.1.0+1
repository: https://github.com/LitGroup/local-date.dart

environment:
  sdk: ^3.1.5

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
